services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent@sha256:352371a7242e8b4aa10958ca02076d1023758070519b89a10251475fb9f1a35a
    container_name: chae-qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - ${DOWNLOADS_ROOT:-/opt/downloads}:/downloads
      - ${MEDIA_ROOT:-/opt/media}:/media
    ports:
      - "127.0.0.1:8080:8080"
      - "${MEDIA_SERVER_IP:-192.168.1.100}:8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - qbittorrent_default

networks:
  qbittorrent_default:
    external: true
