services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent@sha256:352371a7242e8b4aa10958ca02076d1023758070519b89a10251475fb9f1a35a
    container_name: chae-qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - /mnt/media2/downloads:/downloads
      - /mnt/media:/media
    ports:
      - "127.0.0.1:8080:8080"
      - "192.168.1.100:8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - qbittorrent_default

networks:
  qbittorrent_default:
    external: true
