services:
  subgenai:
    image: 'mccloud/subgen@sha256:d26f285ee7ab1f48d45a6b5aea7c1b1f999b16c3770b71eee10e8602ae374cc5'
    container_name: subgenai
    restart: unless-stopped
    volumes:
      - './models:/subgen/models'
      - './subgen.env:/subgen/subgen.env:ro'
      - '/mnt/media:/media:ro'
    environment:
      LOG_LEVEL: debug
      NAME_SERVERS: 9.9.9.9
      PROCADDEDMEDIA: false
      PROCMEDIAONPLAY: false
      CONCURRENT_TRANSCRIPTIONS: 2
      USE_PATH_MAPPING: false
      MODEL_PATH: ./models
    ports:
      - "127.0.0.1:9000:9000"
      - "${MEDIA_SERVER_IP:-192.168.1.100}:9000:9000"
    mem_limit: 4g
