services:
  qbitmanage:
    image: bobokun/qbit_manage@sha256:ea04167f627e506b3691304f4c639a52c05584cc9aea4af7ec87d4ed1299e7f5
    container_name: chae-qbitmanage
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./config:/config
      - ${DOWNLOADS_ROOT:-/mnt/media2/downloads}:/downloads
      - ${MEDIA_ROOT:-/mnt/media}:/media
    command: ["python3", "qbit_manage.py", "--schedule", "720", "--debug"]
    networks:
      - qbittorrent_default

networks:
  qbittorrent_default:
    external: true
