services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr@sha256:6e69e009e1cd7493ff6093e8e187b5d3788c75b4a2c0c5127b6a1beda1c19728
    container_name: chae-recyclarr
    restart: unless-stopped
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config:/config
    networks:
      - qbittorrent_default

networks:
  qbittorrent_default:
    external: true
