services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: chae-homepage
    restart: unless-stopped
    ports:
      - "127.0.0.1:3003:3000"
      - "192.168.1.100:3003:3000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - HOMEPAGE_ALLOWED_HOSTS=127.0.0.1:3003,localhost:3003,192.168.1.100:3003
    networks:
      - qbittorrent_default

networks:
  qbittorrent_default:
    external: true
    name: qbittorrent_default
